In [3]:
import numpy as np

In [4]:
#1 To reverse a vector
a=np.array([1,3,5,7,9])
print('Original array:')
print(a)
print('Reversed array:')
a=a[::-1]
print(a)

Original array:
[1 3 5 7 9]
Reversed array:
[9 7 5 3 1]


In [5]:
#2 To create a 3x3 matrix with values from 0-8
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
#3 To create a 2D array with ones on border and zeros inside
print('Enter array size:')
a=int(input())
b=np.ones((a,a),dtype=np.int16)
b[1:-1,1:-1]=0
print(b)

Enter array size:
4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [7]:
#4 Matrix multiplication
a=np.random.randint(0,10,(5,3))
print(a)
b=np.random.randint(0,10,(3,2))
print(b)
print(np.dot(a,b))

[[9 4 1]
 [5 0 7]
 [7 6 7]
 [0 9 8]
 [8 3 8]]
[[0 8]
 [7 8]
 [9 0]]
[[ 37 104]
 [ 63  40]
 [105 104]
 [135  72]
 [ 93  88]]


In [8]:
#5 Extracting integer part of random array
a=np.random.uniform(0,10,8)
print(a)
print(a-a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(np.trunc(a))
print(np.rint(a))

[5.96721662 9.79347763 0.9699372  8.20462976 6.07880708 9.93518945
 7.66893872 9.49659405]
[5. 9. 0. 8. 6. 9. 7. 9.]
[5. 9. 0. 8. 6. 9. 7. 9.]
[5. 9. 0. 8. 6. 9. 7. 9.]
[5. 9. 0. 8. 6. 9. 7. 9.]
[ 6. 10.  1.  8.  6. 10.  8.  9.]


In [9]:
#6 To check equality of two arrays
a=np.random.uniform(0,12,5)
b=np.random.uniform(0,12,5)
if np.array_equal(a,b):
    print('Arrays are equal')
else:
    print('Arrays are not equal')

Arrays are not equal


In [12]:
#7 To find the nearest value in an array to  a given value
a=np.random.uniform(0,10,10)
print(a)
print('Enter a value')
b=float(input())
c=a[np.abs(a-b).argmin()]
print(c)

[9.58778991 6.15457721 8.86625612 7.37651472 8.7867121  6.27473531
 5.69345818 8.63283848 6.42489909 7.72822243]
Enter a value
8
7.72822243207162


In [33]:
#8 To get the n largest values in an array
a=np.random.randint(0,10,50)
print(a)
a=np.sort(-a)
print(-a)
print('Enter a value')
b=int(input())
a=-a[:b]
print(a)

[5 9 2 6 8 1 3 4 9 7 7 1 5 2 4 4 1 2 6 3 5 7 8 8 7 4 5 6 9 4 1 8 1 9 7 6 1
 1 2 2 9 7 3 0 9 2 2 9 5 5]
[9 9 9 9 9 9 9 8 8 8 8 7 7 7 7 7 7 6 6 6 6 5 5 5 5 5 5 4 4 4 4 4 3 3 3 2 2
 2 2 2 2 2 1 1 1 1 1 1 1 0]
Enter a value
8
[9 9 9 9 9 9 9 8]


In [34]:
#9 To find nearest value to a scalar in  an array
a=np.random.uniform(0,10,10)
print(a)
print('Enter a value')
b=float(input())
c=a[np.abs(a-b).argmin()]
print(c)

[6.16718387 3.02518279 8.08722459 3.10546893 0.31077521 1.23464356
 7.0548462  3.53663531 8.15115259 9.89001279]
Enter a value
8
8.08722458532144


In [35]:
#10 To replace maximum value in an array by -1
a=np.random.randint(0,50,15)
print(a)
a[a.argmax()]=-1
print(a)

[45 29 31  7 31 18 10 22  0 13  4 33 46  6 42]
[45 29 31  7 31 18 10 22  0 13  4 33 -1  6 42]


In [46]:
#11 To find point by point distance in array of shape (100,2)
a=np.random.uniform(1,100,20).reshape(10,2)
b=a[:,:1]
d=a[:,1:2]
d=np.sqrt((b-b.T)**2 + (c-c.T)**2)
print(d)

[[ 0.         72.76596127  1.93071542 30.69897112 67.3113072  40.06568278
  17.12250578 32.67418582  9.73620925 64.60174632]
 [72.76596127  0.         74.69667669 42.06699015  5.45465407 32.7002785
  55.6434555  40.09177545 63.02975202  8.16421495]
 [ 1.93071542 74.69667669  0.         32.62968654 69.24202262 41.99639819
  19.05322119 34.60490124 11.66692467 66.53246174]
 [30.69897112 42.06699015 32.62968654  0.         36.61233608  9.36671166
  13.57646534  1.9752147  20.96276187 33.9027752 ]
 [67.3113072   5.45465407 69.24202262 36.61233608  0.         27.24562443
  50.18880142 34.63712138 57.57509795  2.70956088]
 [40.06568278 32.7002785  41.99639819  9.36671166 27.24562443  0.
  22.943177    7.39149695 30.32947352 24.53606354]
 [17.12250578 55.6434555  19.05322119 13.57646534 50.18880142 22.943177
   0.         15.55168005  7.38629652 47.47924054]
 [32.67418582 40.09177545 34.60490124  1.9752147  34.63712138  7.39149695
  15.55168005  0.         22.93797657 31.92756049]
 [ 9.736209

In [45]:
#12 To sort nth column
a=np.random.randint(0,50,(5,5))
print(a)
print('Enter a value')
n=int(input())
b=a[:,n-1:n]
print(np.sort(b,axis=0))

[[40 35  9 44  0]
 [41 16 17  3 27]
 [31 21 37 48 24]
 [20  3 33  8  0]
 [38 40 35 36  4]]
Enter a value
1
[[20]
 [31]
 [38]
 [40]
 [41]]


In [47]:
#13 To get sum over last two axes of a 4 dimensional array
a=np.random.uniform(1,10,16).reshape(2,2,2,2)
print(a)
print(np.sum(a,axis=(2,3)))

[[[[8.18046094 7.20933662]
   [6.26808464 5.66818957]]

  [[1.29201613 2.00136721]
   [7.94501684 1.47154593]]]


 [[[8.62337048 8.46348443]
   [2.50721621 7.78485888]]

  [[8.93876936 8.22354842]
   [7.92771694 4.47639981]]]]
[[27.32607176 12.70994611]
 [27.37893    29.56643454]]


In [48]:
#14 To find most frequent value in an array
a=np.random.randint(0,10,50)
print(a)
print(np.bincount(a).argmax())

[4 3 6 1 3 2 4 7 6 8 0 1 3 9 7 0 5 0 9 3 2 3 5 6 0 2 2 1 6 1 2 2 8 9 1 8 8
 3 9 7 6 8 9 5 4 7 1 8 4 5]
1
